# The IaC will ensure these envrionment variables are randomly generated
# and injected into the container in the kubernetes environment, so a
# simple docker-compose file is useful for developing the container.

# docker-compose can also be used to mount source code inside the container
# for live-reloading, and to change the entrypoint command.

services:
  web:
    build: .
    ports:
      - "8000:8000"
    links:
      - db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      POSTGRES_HOST: db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
